import { Category } from '@/types/category';

export const DEFAULT_CATEGORIES: Omit<Category, 'membersCount' | 'imageUrl'>[] = [
  {
    id: 'gaming',
    name: 'Gaming',
    icon: 'game-controller',
    color: '#E74C3C',
    description: 'Video games, board games, and everything gaming',
  },
  {
    id: 'music',
    name: 'Music',
    icon: 'musical-notes',
    color: '#9B59B6',
    description: 'Share and discover music of all genres',
  },
  {
    id: 'art',
    name: 'Art & Design',
    icon: 'color-palette',
    color: '#F39C12',
    description: 'Drawing, painting, digital art, and design',
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: 'football',
    color: '#27AE60',
    description: 'All sports and fitness activities',
  },
  {
    id: 'cooking',
    name: 'Cooking',
    icon: 'restaurant',
    color: '#E67E22',
    description: 'Recipes, cooking tips, and food culture',
  },
  {
    id: 'photography',
    name: 'Photography',
    icon: 'camera',
    color: '#3498DB',
    description: 'Photography tips, gear, and sharing photos',
  },
  {
    id: 'reading',
    name: 'Reading',
    icon: 'book',
    color: '#1ABC9C',
    description: 'Books, manga, comics, and literature',
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: 'airplane',
    color: '#2980B9',
    description: 'Travel stories, tips, and destinations',
  },
  {
    id: 'tech',
    name: 'Technology',
    icon: 'hardware-chip',
    color: '#6C5CE7',
    description: 'Tech news, gadgets, and programming',
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: 'barbell',
    color: '#00CEC9',
    description: 'Workouts, health, and wellness',
  },
  {
    id: 'fishing',
    name: 'Fishing',
    icon: 'fish',
    color: '#0984E3',
    description: 'Fishing spots, gear, and catches',
  },
  {
    id: 'movies',
    name: 'Movies & TV',
    icon: 'film',
    color: '#636E72',
    description: 'Movie reviews, TV shows, and cinema',
  },
  {
    id: 'pets',
    name: 'Pets',
    icon: 'paw',
    color: '#E17055',
    description: 'Dogs, cats, and all beloved pets',
  },
  {
    id: 'fashion',
    name: 'Fashion',
    icon: 'shirt',
    color: '#D63031',
    description: 'Style, outfits, and fashion trends',
  },
  {
    id: 'gardening',
    name: 'Gardening',
    icon: 'leaf',
    color: '#00B894',
    description: 'Plants, gardening tips, and green spaces',
  },
  {
    id: 'diy',
    name: 'DIY & Crafts',
    icon: 'construct',
    color: '#FDCB6E',
    description: 'Handmade crafts, woodwork, and DIY projects',
  },
  {
    id: 'anime',
    name: 'Anime & Manga',
    icon: 'sparkles',
    color: '#E84393',
    description: 'Anime, manga, and Japanese pop culture',
  },
  {
    id: 'cars',
    name: 'Cars & Motors',
    icon: 'car-sport',
    color: '#2D3436',
    description: 'Cars, motorcycles, and automotive culture',
  },
  {
    id: 'language',
    name: 'Languages',
    icon: 'globe',
    color: '#0984E3',
    description: 'Language learning and cultural exchange',
  },
  {
    id: 'camping',
    name: 'Camping',
    icon: 'bonfire',
    color: '#D35400',
    description: 'Camping, hiking, and outdoor adventures',
  },
];
